!!dev.wuffs.squatgrow.config.SquatGrowConfig
allowAdventureTwerking: true
chance: 0.25
debug: false
enableMysticalCrops: true
ignoreList: ['minecraft:grass_block', 'minecraft:grass', 'minecraft:tall_grass', 'minecraft:netherrack',
  'minecraft:warped_nylium', 'minecraft:crimson_nylium']
range: 2
useWhitelist: false
